[package]
name = "ir100"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = { version = "0.32.1", features = ["csv", "parquet"] }
anyhow = "1.0"
